#!/bin/bash
perl /guidance.v2.01/www/Guidance/guidance.pl --seqFile ${seq_file} --msaProgram ${params.aligner} --seqType aa --outDir \${PWD} --program GUIDANCE2 --bootstraps 25

mkdir alternativeMSA

tar -zxf MSA.${params.aligner}.Guidance2_AlternativeMSA.tar.gz -C alternativeMSA

for i in alternativeMSA/*.fasta; do
    j=\${i%.fasta}
    t_coffee -other_pg seq_reformat -in \$i -output phylip -out \$j.phylip
done

mv alternativeMSA/*.phylip .
